backend/models/Menu.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "menu".
 *
 * @property int $id
 * @property string $name_ru
 * @property string $name_en
 * @property string $name_fr
 * @property string $name_it
 * @property string $name_de
 * @property int $number
 * @property string $action
 * @property int $status
 * @property string $slug
 * @property string $banner
 */
class Menu extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'menu';
    }

    public $file;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name_ru', 'name_en', 'name_fr', 'name_it', 'name_de', 'number', 'action', 'status', 'slug', 'banner'], 'required'],
            [['number', 'status'], 'integer'],
            [['file'], 'file', 'extensions' => 'jpeg,jpg,png'],
            [['name_ru', 'name_en', 'name_fr', 'name_it', 'name_de', 'action', 'slug', 'banner'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name_ru' => 'Наименование Ru',
            'name_en' => 'Наименование En',
            'name_fr' => 'Наименование Fr',
            'name_it' => 'Наименование It',
            'name_de' => 'Наименование De',
            'number' => 'Порядковый номер',
            'action' => 'Экшн',
            'status' => 'Статус',
            'slug' => 'Слаг',
            'banner' => 'Баннер (1920х380)',
            'file' => 'Баннер (1920х380)',
        ];
    }
}

backend/controllers/MenuController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Menu;
use backend\models\MenuSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * MenuController implements the CRUD actions for Menu model.
 */
class MenuController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'view', 'delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Menu models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MenuSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Menu model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Menu model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Menu();
        $dir = Yii::getAlias('@frontend' . '/web/res/images/menu/');
        if ($model->load(Yii::$app->request->post())) {
            $img_name = uniqid('lifevibes');

            $model->file = UploadedFile::getInstance($model, 'file');
            $model->file->saveAs($dir . $img_name . '.' . $model->file->extension);
            $model->banner = '/res/images/menu/' . $img_name . '.' . $model->file->extension;
            if ($model->save(false)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Menu model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $dir = Yii::getAlias('@frontend' . '/web/res/images/menu/');
        if ($model->load(Yii::$app->request->post())) {
            $img_name = uniqid('lifevibes');

            if(UploadedFile::getInstance($model,'file')){
                if (Yii::getAlias('@frontend' . '/web' . $model->banner)) {
                    try {
                        unlink(Yii::getAlias('@frontend' . '/web' . $model->banner));
                        $model->file = UploadedFile::getInstance($model,'file');
                        $model->file->saveAs($dir.$img_name.'.'.$model->file->extension);
                        $model->banner = '/res/images/menu/'.$img_name.'.'.$model->file->extension;
                        if($model->save(false)){
                            return $this->redirect(['view', 'id' => $model->id]);
                        }

                    } catch (\Exception $e) {
                        $model->file = UploadedFile::getInstance($model,'file');
                        $model->file->saveAs($dir.$img_name.'.'.$model->file->extension);
                        $model->banner = '/res/images/menu/'.$img_name.'.'.$model->file->extension;
                        if($model->save(false)){
                            return $this->redirect(['view', 'id' => $model->id]);
                        }
                    }
                }else{
                    $model->file = UploadedFile::getInstance($model,'file');
                    $model->file->saveAs($dir.$img_name.'.'.$model->file->extension);
                    $model->banner = '/res/images/menu/'.$img_name.'.'.$model->file->extension;
                    if($model->save(false)){
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                }
            }else{
                if($model->save(false)){
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Menu model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Menu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Menu the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Menu::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/MenuController.php
<?php
/**
 * Created by PhpStorm.
 * User: Jianbaev Jasur djianbaev.dj@gmail.com
 * Date: 03.04.2020
 * Time: 14:20
 */

namespace frontend\controllers;


use backend\models\About;
use backend\models\city\City;
use backend\models\city\GuideGallery;
use backend\models\city\GuideItem;
use backend\models\city\GuideMenu;
use backend\models\info\InfoItem;
use backend\models\info\InfoMenu;
use backend\models\Menu;
use backend\models\Plus;
use backend\models\PlusItem;
use backend\models\Team;
use backend\models\TeamItem;
use backend\models\tour\Service;
use backend\models\tour\ServiceItem;
use backend\models\tour\Tour;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class MenuController extends Controller
{
    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        $slug = Yii::$app->request->get('menu_slug');
        $model = Menu::find()->where(['slug' => $slug])->asArray()->one();
        if (!empty($model)) {
            switch ($model['action']) {
                case 'menu/about':
                    $rowA = About::find()->asArray()->one();
                    $rowP = Plus::find()->asArray()->one();
                    $rowPI = PlusItem::find()->asArray()->all();
                    $rowT = Team::find()->asArray()->one();
                    $rowTI = TeamItem::find()->asArray()->all();

                    return $this->render('page_about', [
                        'model' => $model,
                        'rowA' => $rowA,
                        'rowP' => $rowP,
                        'rowPI' => $rowPI,
                        'rowT' => $rowT,
                        'rowTI' => $rowTI
                    ]);
                    break;
                case 'menu/guide':
                    $rowG = GuideMenu::find()->where(['status' => 1])->orderBy(['number' => SORT_ASC])->asArray()->all();

                    $cities = City::find()->where(['status' => 1])->asArray()->all();
                    $menus = GuideMenu::find()->where(['status' => 1])->asArray()->all();
                    $datas = [];

//                    foreach ($cities as $city) {
//                        $datas[$city['id']]['city'] = $city;
//                        foreach ($menus as $menu){
//                            $items = GuideItem::find()->where(['status'=>1,'guide_menu_id'=>$menu['id'],'city_id'=>$city['id']])->asArray()->limit(3)->all();
//                            $datas[$city['id']][$menu['id']] = $menu;
//                            $datas[$city['id']][$menu['id']]['items'] = $items;
//                        }
//                    }


                    return $this->render('page_guide', [
                        'model' => $model,
                        //'datas' => $datas,
                        //'cities' => $cities,
                        //'menus' => $menus,
                        'rowG' => $rowG
                    ]);
                    break;
                case 'menu/experience':
                    $tours = Tour::find()->limit(4)->asArray()->all();

                    $datas = [];
                    $services = Service::find()->asArray()->all();
                    foreach ($services as $service){
                        $items = ServiceItem::find()->where(['service_id'=>$service['id']])->limit(3)->asArray()->all();
                        if(!empty($items)){
                            $datas[$service['id']] = $items;
                        }
                    }

                    return $this->render('page_exp',[
                        'model'=>$model,
                        'tours'=>$tours,
                        'services'=>$services,
                        'datas'=>$datas
                    ]);
                    break;
                case 'menu/regionalinfo':
                    $rowI = InfoMenu::find()->where(['status' => 1])->orderBy(['number' => SORT_ASC])->asArray()->all();
                    return $this->render('page_info', [
                        'model' => $model,
                        'rowI' => $rowI
                    ]);
                    break;
                case 'menu/application':
                    $lang = Yii::$app->language;
                    switch ($lang){
                        case 'ru':
                            $this->view->registerJsFile('/res/sweetalert/sweetalert2.all.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
                            $this->view->registerCssFile('/res/sweetalert/sweetalert2.min.css');
                            return $this->render('application/ru',[
                                'model'=>$model
                            ]);
                            break;
                        case 'en':
                            $this->view->registerJsFile('/res/sweetalert/sweetalert2.all.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
                            $this->view->registerCssFile('/res/sweetalert/sweetalert2.min.css');
                            return $this->render('application/en',[
                                'model'=>$model
                            ]);
                            break;
                        case 'fr':
                            $this->view->registerJsFile('/res/sweetalert/sweetalert2.all.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
                            $this->view->registerCssFile('/res/sweetalert/sweetalert2.min.css');
                            return $this->render('application/fr',[
                                'model'=>$model
                            ]);
                            break;
                        case 'it':
                            $this->view->registerJsFile('/res/sweetalert/sweetalert2.all.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
                            $this->view->registerCssFile('/res/sweetalert/sweetalert2.min.css');
                            return $this->render('application/it',[
                                'model'=>$model
                            ]);
                            break;
                    }

                    break;
            }
        } else {
            throw new NotFoundHttpException();
        }
    }





    /**** about ***/

    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionUs()
    {
        $model = Menu::find()->where(['action' => 'menu/about'])->asArray()->one();
        if (!empty($model)) {
            $rowA = About::find()->asArray()->one();
            return $this->render('page_about_us', [
                'model' => $model,
                'rowA' => $rowA,
            ]);
        } else {
            throw new NotFoundHttpException();
        }
    }

    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionExcellence()
    {
        $model = Menu::find()->where(['action' => 'menu/about'])->asArray()->one();
        if (!empty($model)) {
            $rowP = Plus::find()->asArray()->one();
            $rowPI = PlusItem::find()->asArray()->all();
            return $this->render('page_about_excellence', [
                'model' => $model,
                'rowP' => $rowP,
                'rowPI' => $rowPI,
            ]);
        } else {
            throw new NotFoundHttpException();
        }
    }

    public function actionOurteam()
    {
        $model = Menu::find()->where(['action' => 'menu/about'])->asArray()->one();
        if (!empty($model)) {
            $rowT = Team::find()->asArray()->one();
            $rowTI = TeamItem::find()->asArray()->all();
            return $this->render('page_about_ourteam', [
                'model' => $model,
                'rowT' => $rowT,
                'rowTI' => $rowTI,
            ]);
        } else {
            throw new NotFoundHttpException();
        }
    }


    /*** guide ***/
    public function actionHeaderguide()
    {
        $menu_slug = Yii::$app->request->get('menu_slug');
        $guide_slug = Yii::$app->request->get('guide_slug');

        $model = Menu::find()->where(['slug' => $menu_slug, 'action' => 'menu/guide'])->asArray()->one();
        if (!empty($model)) {
            $guide = GuideMenu::find()->where(['slug' => $guide_slug])->asArray()->one();
            if (!empty($guide)) {

                /*** filter ***/
                if (Yii::$app->request->get('city')) {
                    $get_cities = Yii::$app->request->get('city');
                    $items = [];
                    $f_cities = [];
                    foreach ($get_cities as $get_city) {
                        if (is_numeric($get_city)) {
                            $db = GuideItem::find()->where(['guide_menu_id' => $guide['id'], 'city_id' => $get_city])->orderBy(['top' => SORT_DESC])->asArray()->all();
                        }
                        $items[$get_city] = $db;
                    }

                    $cities = City::find()->where(['status' => 1])->asArray()->all();
                    foreach ($cities as $record){
                        $f_cities[$record['id']] = $record;
                    }

                    return $this->render('page_guide_items_header_filter', [
                        'model' => $model,
                        'guide' => $guide,
                        'items' => $items,
                        'f_cities' => $f_cities,
                        'cities' => $cities
                    ]);
                }
                /**** end filter ***/
                $items = GuideItem::find()->where(['guide_menu_id' => $guide['id']])->orderBy(['top' => SORT_DESC])->asArray()->all();
                $cities = City::find()->where(['status' => 1])->asArray()->all();

                return $this->render('page_guide_items_header', [
                    'model' => $model,
                    'guide' => $guide,
                    'items' => $items,

frontend/views/menu/page_about_excellence.php
<?php
/**
 * Created by PhpStorm.
 * User: Jianbaev Jasur djianbaev.dj@gmail.com
 * Date: 03.04.2020
 * Time: 14:40
 */

use yii\helpers\Url;

/* @var $this \yii\web\View */

$lang = Yii::$app->language;

$this->title = $rowP['title_' . $lang];
?>

<section class="page-banner">
    <div class="image-layer" style="background-image:url(<?php echo $model['banner'] ?>);"></div>

    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1><?php echo $rowP['title_' . $lang] ?></h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="/"><?php echo Yii::$app->params['pMain'][$lang]?></a></li>
                        <li><a href="<?php echo Url::to(['menu/index','menu_slug'=>$model['slug']]) ?>"><?php echo $model['name_' . $lang] ?></a></li>
                        <li><?php echo $rowP['title_' . $lang] ?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="welcome-section">
    <div class="auto-container">
        <div class="title-box wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
            <h2><?php echo $rowP['title_' . $lang] ?></h2>
            <div class="text"><?php echo $rowP['text_' . $lang] ?></div>
        </div>
    </div>
</section>

<section class="features-section">
    <div class="auto-container">
        <div class="row clearfix">
            <?php if (!empty($rowPI)): ?>
                <?php foreach ($rowPI as $plus): ?>
                    <div class="feature-block col-lg-4 col-md-6 col-sm-12">
                        <div class="inner-box">
                            <div class="icon-box">
                                <img src="<?php echo $plus['image'] ?>"/>
                            </div>
                            <div class="content">
                                <h4><?php echo $plus['name_' . $lang] ?></h4>
                                <div class="text"><?php echo $plus['text_' . $lang] ?></div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</section>

frontend/views/menu/page_about_ourteam.php
<?php
/**
 * Created by PhpStorm.
 * User: Jianbaev Jasur djianbaev.dj@gmail.com
 * Date: 03.04.2020
 * Time: 14:40
 */

use yii\helpers\Url;

/* @var $this \yii\web\View */

$lang = Yii::$app->language;

$this->title = $rowT['title_' . $lang];
?>

<section class="page-banner">
    <div class="image-layer" style="background-image:url(<?php echo $model['banner'] ?>);"></div>

    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1><?php echo $rowT['title_' . $lang] ?></h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="/"><?php echo Yii::$app->params['pMain'][$lang]?></a></li>
                        <li><a href="<?php echo Url::to(['menu/index','menu_slug'=>$model['slug']]) ?>"><?php echo $model['name_' . $lang] ?></a></li>
                        <li><?php echo $rowT['title_' . $lang] ?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>



<!--team-->
<section class="team-section">
    <div class="auto-container">
        <div class="sec-title centered">
            <h2><?php echo $rowT['title_' . $lang] ?></h2>
            <div class="text"><?php echo $rowT['text_' . $lang] ?></div>
        </div>

        <div class="team-box">
            <div class="row clearfix">
                <?php if (!empty($rowTI)): ?>
                    <?php $sec = 0; ?>
                    <?php for ($i = 0; $i < count($rowTI); $i++): ?>
                        <?php $sec += 500; ?>

                        <div class="team-block col-lg-4 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="0ms"
                             data-wow-duration="<?php echo (1000+$sec);?>ms">
                            <div class="inner-box">
                                <div class="image-box">
                                    <a href="#"><img src="<?php echo $rowTI[$i]['image']?>" alt="" title=""></a>
                                </div>
                                <div class="lower-box clearfix">
                                    <div class="lower-content">
                                        <h4><a href="#"><?php echo str_replace(' ','<br>',$rowTI[$i]['fio_'.$lang]);?></a></h4>
                                        <div class="designation"><?php echo $rowTI[$i]['position_'.$lang]?></div>
                                        <div class="designation"><i class="flaticon-envelope"></i> <?php echo $rowTI[$i]['email']?></div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    <?php endfor; ?>
                <?php endif; ?>
            </div>
        </div>


    </div>
</section>

frontend/views/menu/page_about_us.php
<?php
/**
 * Created by PhpStorm.
 * User: Jianbaev Jasur djianbaev.dj@gmail.com
 * Date: 03.04.2020
 * Time: 14:40
 */

use yii\helpers\Url;

/* @var $this \yii\web\View */

$lang = Yii::$app->language;

$this->title = $rowA['title_' . $lang];
?>

<section class="page-banner">
    <div class="image-layer" style="background-image:url(<?php echo $model['banner'] ?>);"></div>

    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1><?php echo $rowA['title_' . $lang] ?></h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="/"><?php echo Yii::$app->params['pMain'][$lang]?></a></li>
                        <li><a href="<?php echo Url::to(['menu/index','menu_slug'=>$model['slug']]) ?>"><?php echo $model['name_' . $lang] ?></a></li>
                        <li><?php echo $rowA['title_' . $lang] ?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<!--about-->

<section class="welcome-section">
    <div class="auto-container">
        <div class="title-box wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
            <h2><?php  $rowA['title_' . $lang] ?></h2>
            <div class="text"><?php echo $rowA['text_' . $lang] ?></div>
        </div>
        <div class="image-box wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
            <img src="<?php echo $rowA['image'] ?>" alt="">
        </div>
    </div>
</section>

frontend/views/menu/page_guide_item.php
<?php
/**
 * Created by PhpStorm.
 * User: Jianbaev Jasur djianbaev.dj@gmail.com
 * Date: 03.04.2020
 * Time: 14:40
 */

use yii\helpers\Url;

/* @var $this \yii\web\View */

$lang = Yii::$app->language;

$this->title = $item['name_' . $lang];
?>

<section class="page-banner">
    <div class="image-layer" style="background-image:url(<?php echo $model['banner'] ?>);"></div>

    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1><?php echo $item['name_' . $lang] ?></h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="/"><?php echo Yii::$app->params['pMain'][$lang]?></a></li>
                        <li><a href="<?php echo Url::to(['menu/index','menu_slug'=>$model['slug']]) ?>"><?php echo $model['name_' . $lang] ?></a></li>
                        <li><a href="<?php echo Url::to(['menu/headerguide','menu_slug'=>$model['slug'],'guide_slug'=>$guide['slug']]) ?>">
                                <?php echo $guide['name_' . $lang] ?></a></li>
                        <li><?php echo $item['name_' . $lang] ?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">

            <div class="content-side col-lg-12 col-md-12 col-sm-12" style="margin-bottom: unset;">
                <div class="blog-content">
                    <div class="news-post-details">

                        <!--News Block-->
                        <div class="news-block-six">
                            <div class="inner-box">
                                <div class="image-box">
                                    <figure class="image">
                                        <img src="<?php echo $item['image']?>" alt="" title="">
                                    </figure>
                                </div>
                                <div class="content-box">
                                    <div class="inner">
                                        <div class="content lv-content">
                                            <h3><?php echo $item['name_'.$lang]?></h3>
                                            <div class="text">
                                                <?php echo $item['text_'.$lang]?>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>


                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


<?php if(!empty($images)):?>
<section class="portfolio-section portfolio-two-column" style="padding: unset;">
    <div class="auto-container">
        <div class="row clearfix">
            <?php foreach ($images as $image):?>
            <div class="gallery-block-two col-lg-4 col-md-4 col-sm-6 wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
                <div class="inner-box">
                    <div class="image-box">
                        <figure class="image">
                            <a class="lightbox-image" href="<?php echo $image['image']?>"><img src="<?php echo $image['image']?>" alt=""></a>
                        </figure>
                        <div class="zoom-btn">
                            <a class="lightbox-image zoom-link" href="<?php echo $image['image']?>" data-fancybox="gallery"><span class="icon flaticon-expand"></span></a>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach;?>
        </div>

    </div>
</section>
<?php endif;?>

frontend/views/menu/page_info_item.php
<?php
/**
 * Created by PhpStorm.
 * User: Jianbaev Jasur djianbaev.dj@gmail.com
 * Date: 03.04.2020
 * Time: 14:40
 */

use yii\helpers\Url;

/* @var $this \yii\web\View */

$lang = Yii::$app->language;

$this->title = $item['name_' . $lang];
?>

<section class="page-banner">
    <div class="image-layer" style="background-image:url(<?php echo $model['banner'] ?>);"></div>

    <div class="banner-inner">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1><?php echo $item['name_' . $lang] ?></h1>
                <div class="page-nav">
                    <ul class="bread-crumb clearfix">
                        <li><a href="/"><?php echo Yii::$app->params['pMain'][$lang]?></a></li>
                        <li><a href="<?php echo Url::to(['menu/index','menu_slug'=>$model['slug']]) ?>"><?php echo $model['name_' . $lang] ?></a></li>
                        <li><?php echo $item['name_' . $lang] ?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">

            <div class="content-side col-lg-12 col-md-12 col-sm-12" style="margin-bottom: unset;">
                <div class="blog-content">
                    <div class="news-post-details">

                        <!--News Block-->
                        <div class="news-block-six">
                            <div class="inner-box">

                                <div class="content-box">
                                    <div class="inner">
                                        <div class="content lv-content">
                                            <h3><?php echo $item['name_'.$lang]?></h3>
                                            <div class="text">
                                                <?php echo $item['text_'.$lang]?>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <div class="image-box">
                                    <figure class="image">
                                        <img src="<?php echo $item['image']?>" alt="" title="">
                                    </figure>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>

        </div>
    </div>
</div>